### ISSUE TITLE
Layout shifting on interaction

### ISSUE THREAD

**Issue by fogrew** [mightybittern/Diploma-Project#10]
> **16. 💛 Interactions( :hover, :active и :focus) should not change the document flow.**
> Adjacent elements should not change their position and size unless specified in the style guide.

1. When I focus input in first screen, everything else next are moving for two pixels down. It's because you're adding a border on `:focus`. That's okay to add border for focus, but you can use the trick: make input with transparent border by default and change color of it on focus. The same fix is required for select on the contact page.
```css
.input {
    border: 1px solid transparent;
}
.input:focus {
    border-color: #22222226;
}
```

2. When I'm toggling FAQ sections, they're enlarging for a moment and then returning back their dimensions. To solve this issue, you can think about on which elements are `padding` is represented.
